export const COMPANY_STAFF_REQUEST = "COMPANY_STAFF_REQUEST";
export const COMPANY_STAFF_SUCCESS = "COMPANY_STAFF_SUCCESS";
export const COMPANY_INVITATIONS_REQUEST = "COMPANY_INVITATIONS_REQUEST";
export const COMPANY_INVITATIONS_SUCCESS = "COMPANY_INVITATIONS_SUCCESS";
export const INVITE_USER_TO_COMPANY = "INVITE_USER_TO_COMPANY";
export const INVITE_USER_TO_COMPANY_SUCCESS = "INVITE_USER_TO_COMPANY_SUCCESS";
export const UPDATE_COMPANY_USER = "UPDATE_COMPANY_USER";
export const UPDATE_COMPANY_USER_SUCCESS = "UPDATE_COMPANY_USER_SUCCESS";
export const UPDATE_COMPANY_INVITED_USER = "UPDATE_COMPANY_INVITED_USER";
export const UPDATE_COMPANY_INVITED_USER_SUCCESS =
  "UPDATE_COMPANY_INVITED_USER_SUCCESS";
export const REINVITE_USER_REQUEST = "REINVITE_USER_REQUEST";
export const REINVITE_USER_SUCCESS = "REINVITE_USER_SUCCESS";
export const DELETE_STAFF_MEMBER_REQUEST = "DELETE_STAFF_MEMBER_REQUEST";
export const DELETE_STAFF_MEMBER_SUCCESS = "DELETE_STAFF_MEMBER_SUCCESS";
export const DELETE_INVITED_MEMBER_REQUEST = "DELETE_INVITED_MEMBER_REQUEST";
export const DELETE_INVITED_MEMBER_SUCCESS = "DELETE_INVITED_MEMBER_SUCCESS";
export const STAFF_MEMBER_REQUEST = "STAFF_MEMBER_REQUEST";
export const STAFF_MEMBER_SUCCESS = "STAFF_MEMBER_SUCCESS";
export const ACCOUNT_SPECIALIZATIONS_REQUEST =
  "ACCOUNT_SPECIALIZATIONS_REQUEST";
export const ACCOUNT_SPECIALIZATIONS_SUCCESS =
  "ACCOUNT_SPECIALIZATIONS_SUCCESS";
export const BRANCH_SPECIALIZATIONS_REQUEST = "BRANCH_SPECIALIZATIONS_REQUEST";
export const BRANCH_SPECIALIZATIONS_SUCCESS = "BRANCH_SPECIALIZATIONS_SUCCESS";
export const DELETE_APPROVED_MEMBER_REQUEST = "DELETE_APPROVED_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_COMPANY_STAFF_SUCCESS";
export const ADD_MEMBER_SPECIALIZATIONS_REQUEST =
  "ADD_MEMBER_SPECIALIZATIONS_REQUEST";
export const ADD_MEMBER_SPECIALIZATIONS_SUCCESS =
  "ADD_MEMBER_SPECIALIZATIONS_SUCCESS";
export const EDIT_MEMBER_SPECIALIZATIONS_REQUEST =
  "EDIT_MEMBER_SPECIALIZATIONS_REQUEST";
export const EDIT_MEMBER_SPECIALIZATIONS_SUCCESS =
  "EDIT_MEMBER_SPECIALIZATIONS_SUCCESS";
export const DELETE_MEMBER_SPECIALIZATIONS_REQUEST =
  "DELETE_MEMBER_SPECIALIZATIONS_REQUEST";
export const DELETE_MEMBER_SPECIALIZATIONS_SUCCESS =
  "DELETE_MEMBER_SPECIALIZATIONS_SUCCESS";
export const ACCOUNT_BRANCHES_SUCCESS = "ACCOUNT_BRANCHES_SUCCESS";

// custom day
export const CUSTOM_DAY_SCHEDULE_REQUEST = "CUSTOM_DAY_SCHEDULE_REQUEST";
export const CUSTOM_DAY_SCHEDULE_SUCCESS = "CUSTOM_DAY_SCHEDULE_SUCCESS";
export const ADD_CUSTOM_DAY_SCHEDULE_REQUEST =
  "ADD_CUSTOM_DAY_SCHEDULE_REQUEST";
export const ADD_CUSTOM_DAY_SCHEDULE_SUCCESS =
  "ADD_CUSTOM_DAY_SCHEDULE_SUCCESS";
export const DELETE_CUSTOM_DAY_SCHEDULE_PATTERN =
  "DELETE_CUSTOM_DAY_SCHEDULE_PATTERN";
export const DELETE_CUSTOM_DAY_SCHEDULE_PATTERN_SUCCESS =
  "DELETE_CUSTOM_DAY_SCHEDULE_PATTERN_SUCCESS";
// custom
export const CUSTOM_SCHEDULE_TEMPLATE = "CUSTOM_SCHEDULE_TEMPLATE";
export const CUSTOM_SCHEDULE_TEMPLATE_SUCCESS =
  "CUSTOM_SCHEDULE_TEMPLATE_SUCCESS";
export const ADD_CUSTOM_SCHEDULE_REQUEST = "ADD_CUSTOM_SCHEDULE_REQUEST";
export const ADD_CUSTOM_SCHEDULE_SUCCESS = "ADD_CUSTOM_SCHEDULE_SUCCESS";
export const TOGGLE_CUSTOM_SCHEDULE_ACTIVITY =
  "TOGGLE_CUSTOM_SCHEDULE_ACTIVITY";
export const TOGGLE_CUSTOM_SCHEDULE_ACTIVITY_SUCCESS =
  "TOGGLE_CUSTOM_SCHEDULE_ACTIVITY_SUCCESS";
// weekly
export const WEEKLY_SCHEDULE_TEMPLATE_REQUEST =
  "WEEKLY_SCHEDULE_TEMPLATE_REQUEST";
export const WEEKLY_SCHEDULE_TEMPLATE_SUCCESS =
  "WEEKLY_SCHEDULE_TEMPLATE_SUCCESS";
export const ADD_ACCOUNT_SCHEDULE_REQUEST = "ADD_ACCOUNT_SCHEDULE_REQUEST";
export const ADD_ACCOUNT_SCHEDULE_SUCCESS = "ADD_ACCOUNT_SCHEDULE_SUCCESS";
export const UPDAT_ACCOUNT_SCHEDULE = "UPDAT_ACCOUNT_SCHEDULE";
export const UPDAT_ACCOUNT_SCHEDULE_SUCCESS = "UPDAT_ACCOUNT_SCHEDULE_SUCCESS";
export const DELETE_ACCOUNT_SCHEDULE = "DELETE_ACCOUNT_SCHEDULE";
export const DELETE_ACCOUNT_SCHEDULE_SUCCESS =
  "DELETE_ACCOUNT_SCHEDULE_SUCCESS";
