export const USER_APPOINTMENT_LIST_REQUEST = "USER_APPOINTMENT_LIST_REQUEST";
export const USER_APPOINTMENT_LIST_SUCCESS = "USER_APPOINTMENT_LIST_SUCCESS";
export const RESOURCE_APPOINTMENT_LIST_REQUEST =
  "RESOURCE_APPOINTMENT_LIST_REQUEST";
export const APPOINTMENT_LIST_SIGNALR_START = "APPOINTMENT_LIST_SIGNALR_START";
export const ADD_USER_APPOINTMENT_REQUEST = "ADD_USER_APPOINTMENT_REQUEST";
export const ADD_USER_APPOINTMENT_SUCCESS = "ADD_USER_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";
export const DELETE_USER_APPOINTMENT_SUCCESS =
  "DELETE_USER_APPOINTMENT_SUCCESS";
export const DELETE_RESOURCE_APPOINTMENT_SUCCESS =
  "DELETE_RESOURCE_APPOINTMENT_SUCCESS";

export const APPOINTMENT_BY_ID_REQUEST = "APPOINTMENT_BY_ID_REQUEST";
export const APPOINTMENT_BY_ID_SUCCESS = "APPOINTMENT_BY_ID_SUCCESS";

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";

export const UPDATE_TIME_BLOCKER_REQUEST = "UPDATE_TIME_BLOCKER_REQUEST";
export const DELETE_TIME_BLOCKER_REQUEST = "DELETE_TIME_BLOCKER_REQUEST";

export const UPDATE_APPOINTMENT_STEP_REQUEST =
  "UPDATE_APPOINTMENT_STEP_REQUEST";
export const UPDATE_USER_APPOINTMENT_STEP_SUCCESS =
  "UPDATE_USER_APPOINTMENT_STEP_SUCCESS";

export const ADD_RESOURCE_APPOINTMENT_SUCCESS =
  "ADD_RESOURCE_APPOINTMENT_SUCCESS";
export const UPDATE_RESOURCE_APPOINTMENT_STEP_SUCCESS =
  "UPDATE_RESOURCE_APPOINTMENT_STEP_SUCCESS";

export const ADD_BLOCK_TIME_REQUEST = "ADD_BLOCK_TIME_REQUEST";
export const ADD_BLOCK_TIME_SUCCESS = "ADD_BLOCK_TIME_SUCCESS";

export const CALENDAR_PRINT_DATA_SUCCESS = "CALENDAR_PRINT_DATA_SUCCESS";

export const ADD_STEP_REQUEST = "ADD_STEP_REQUEST";
export const CALENDAR_DEFAULT_WIDTH = 76;

export const RESOURCE_APPOINTMENT_LIST_SUCCESS =
  "RESOURCE_APPOINTMENT_LIST_SUCCESS";

export const APPOINTMENT_LIST_SIGNALR_CLOSE = "APPOINTMENT_LIST_SIGNALR_CLOSE";

export const TIME_SLOTS_REQUEST = "TIME_SLOTS_REQUEST";
export const TIME_SLOTS_SUCCESS = "TIME_SLOTS_SUCCESS";

export const GET_USER_APPOINTMENT_REQUEST = "GET_USER_APPOINTMENT_REQUEST";
export const GET_USER_APPOINTMENT_SUCCESS = "GET_USER_APPOINTMENT_SUCCESS";

export const CALENDAR_PRINT_DATA_REQUEST = "CALENDAR_PRINT_DATA_REQUEST";
export const CALENDAR_LOADING = "CALENDAR_LOADING";
export const DISABLE_BUTTON = "DISABLE_BUTTON";

export const GET_PROVIDERS_SUGGESTIONS_LIST = "GET_PROVIDERS_SUGGESTIONS_LIST";
export const GET_PROVIDERS_SUGGESTIONS_LIST_SUCCESS =
  "GET_PROVIDERS_SUGGESTIONS_LIST_SUCCESS";

export const SEARCH_USER_APPOINTMENTS = "SEARCH_USER_APPOINTMENTS";
export const SEARCH_USER_APPOINTMENTS_SUCCESS =
  "SEARCH_USER_APPOINTMENTS_SUCCESS";

export const FILTER_USER_APPOINTMENTS = "FILTER_USER_APPOINTMENTS";
export const RESET_ADVANCED_SEARCH_VALUES = "RESET_ADVANCED_SEARCH_VALUES";

export const RESET_USER_APPOINTMENTS_LIST = "RESET_USER_APPOINTMENTS_LIST";
