export const GET_TEMPLATE_LIST_REQUEST = "GET_TEMPLATE_LIST_REQUEST";
export const GET_TEMPLATE_LIST_SUCCESS = "GET_TEMPLATE_LIST_SUCCESS";
export const GET_TEMPLATE_DATA_REQUEST = "GET_TEMPLATE_DATA_REQUEST";
export const GET_TEMPLATE_DATA_SUCCESS = "GET_TEMPLATE_DATA_SUCCESS";
export const GET_TEMPLATE_PAGINATION = "GET_TEMPLATE_PAGINATION";

export const EDIT_TEMPLATE_REQUEST = "EDIT_TEMPLATE_REQUEST";
export const EDIT_TEMPLATE_SUCCESS = "EDIT_TEMPLATE_SUCCESS";

export const DELETE_TEMPLATE_REQUEST = "DELETE_TEMPLATE_REQUEST";
export const DELETE_TEMPLATE_SUCCESS = "DELETE_TEMPLATE_SUCCESS";

export const ADD_TEMPLATE_REQUEST = "ADD_TEMPLATE_REQUEST";
export const ADD_TEMPLATE_SUCCESS = "ADD_TEMPLATE_SUCCESS";

export const SCHEDULE_LIST_REQUEST = "SCHEDULE_LIST_REQUEST";
export const SCHEDULE_LIST_SUCCESS = "SCHEDULE_LIST_SUCCESS";
export const RESET_SCHEDULE_LIST = "RESET_SCHEDULE_LIST";

export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
